### ISSUE TITLE
The original error cannot be read

### ISSUE THREAD

**Issue by marvelph** [tenntenn/natureremo#6]
Hello.

Passing an invalid access token to "NewClient()" would normally cause an authentication error, but in fact the following error will occur.

`2021/01/01 17:42:37 GET users/me failed: cannot get X-Rate-Limit-Limit from header`

Isn't the check by "RateLimitFromHeader()" hiding the API error?

**Comment by tenntenn** [comment]
Fix at #9

**Comment by marvelph** [comment]
@tenntenn 

Thanks for the fix.
We are now able to identify authentication errors.
